name: Build aGain

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgtk-3-dev libasound2-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload VST3 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aGain-${{matrix.os}}
          path: build/aGain_artefacts/${{env.BUILD_TYPE}}/VST3/*.vst3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}